version: "3"

volumes:
  pgkwil:
    driver: local

services:
  db:
    image: kwildb/postgres:16.5-1
    ports:
      - "5432"
    restart: always
    user: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: --data-checksums
    networks:
      - kwilnet0
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 && sleep 1"]
      interval: 2s
      timeout: 6s
      retries: 10

  kwild:
    image: kwild-reward:latest
    ports:
      - "8484:8484"
    environment:
      GORACE: "halt_on_error=1 log_path=/app/kwil/datarace"
    volumes:
      - type: bind
        source: { { .TestnetDir } }/{{ .NodeServicePrefix }}{{ .NodeNumber }}
        target: /app/kwil
    networks:
      - { { .Network } }
    depends_on:
      { { .PGServicePrefix } }{ { .NodeNumber } }:
        condition: service_healthy
    command: |
      start
      --root=/app/kwil
      --log-format=plain
      --admin.listen=/tmp/kwild.socket
      --rpc.listen=0.0.0.0:8484
      --p2p.listen=0.0.0.0:6600
      --db.host={{ .PGServicePrefix }}{{ .NodeNumber }}
      --db.port=5432
      --db.user=kwild
      --db.pass=kwild
    healthcheck:
      test: [ "CMD", "curl", "--fail-with-body", "-s", "http://127.0.0.1:8484/api/v1/health/user" ]
      interval: 2s
      timeout: 6s
      retries: 10

networks:
  kwilnet0:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.5.100.0/23