#volumes:
#  pgkwil:
#    driver: local

services:
#  pg:
#    container_name: postgres
#    image: kwildb/postgres:16.4-1
#    ports:
#      - "5432:5432"
#    restart: always
#    environment:
#      POSTGRES_HOST_AUTH_METHOD: trust
#      POSTGRES_INITDB_ARGS: --data-checksums
#      # Setting user/pass/db works, but we use docker-entrypoint-initdb.d instead for more control
#      # POSTGRES_USER: kwild
#      # POSTGRES_PASSWORD: kwild
#      # POSTGRES_DB: kwild
#    volumes:
#      - /var/lib/postgresql/data

  db:
    image: kwildb/postgres:16.5-1
    ports:
      - "5432"
    restart: always
    user: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: --data-checksums
    volumes:
      - /var/lib/postgresql/data
    networks:
      - kwil-reward
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 && sleep 1"]
      interval: 2s
      timeout: 6s
      retries: 10

  kwild:
    image: kwil-reward:latest
    env_file: sim.env
    ports:
      - "8484:8484"
      - "6600:6600"
    environment:
      GORACE: "halt_on_error=1 log_path=/app/kwil/datarace"
    volumes:
      - type: bind
        source: /tmp/.testnet/node0
        target: /app/kwil
    networks:
      - kwil-reward
    depends_on:
      db:
        condition: service_healthy
    command: |
      start
      --root=/app/kwil
      --log-format=plain
      --admin.listen=/tmp/kwild.socket
      --rpc.listen=0.0.0.0:8484
      --p2p.listen=0.0.0.0:6600
      --db.host=db
      --db.port=5432
      --db.user=kwild
      --db.pass=kwild
      --consensus.empty-block-timeout=1s
#    healthcheck:
#      test: [ "CMD", "curl", "--fail-with-body", "-s", "http://127.0.0.1:8484/api/v1/health/user" ]
#      interval: 2s
#      timeout: 6s
#      retries: 10

  signer:
    image: kwil-reward-signer:latest
    env_file: sim.env
    build:
      context: ./peripheral/goimpl
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: /tmp/kwil-signersvc-config.json
        target: /conf/config.json
    networks:
      - kwil-reward
    command: /app/signersvc /conf/config.json
    depends_on:
      - kwild
#    depends_on:
#      kwild:
#        condition: service_healthy

  poster:
    image: kwil-reward-poster:latest
    env_file: sim.env
    build:
      context: .
      dockerfile: ./peripheral/poster/Dockerfile
    networks:
      - kwil-reward
    volumes:
      - type: bind
        source: /tmp/kwil-postersvc-config.json
        target: /conf/config.json
    command: npx tsx peripheral/poster/cli.ts /conf/config.json
    depends_on:
      - kwild
#    depends_on:
#      kwild:
#        condition: service_healthy

networks:
  kwil-reward:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.5.100.0/23